function myAlerts() {
// this runs based on daily trigger
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = ss.getSheetByName("Reminders");
  
  var range = sheet.getDataRange();
  var values = range.getDisplayValues();
  
  var lastRow = range.getLastRow();
  
  var message = "";
  var sheetUrl = ss.getUrl();
  
  var anyMatches = 'False';
  
  var email = Session.getActiveUser().getEmail();  

     
  for (var i = 5; i < lastRow; i++)  
  {  
   // if today matches the alert date, send an alert
   
   if (values[i][3] == 'True')
   {  
     // add a message for this row if date matches
     message = message + values[i][0] + " is due on the " + values[i][1] + "<br />\n";
     
     anyMatches = true;  
     
     
   }  
  }  // ends for loop
  
  // footer for message
  message = message +  "<br />\nThis reminder was generated by this spreadsheet: <br />\n" + sheetUrl;
 
 if(anyMatches)
 {
  // if there is a match,email gets sent
       MailApp.sendEmail({
      to: email,
      subject: 'Email Reminder',
      htmlBody: message});
}
  
 }